const kpiToEndpointMapping = {
    'Cost Per Lead': ['marketingExpenses', 'leads'],
    'Lead Connections': ['leads', 'leadConnections'],
    'Triage Calls': ['leadConnections', 'triageCalls'],
    'Qualified Triage Calls': ['triageCalls', 'qualifiedTriageCalls'],
    'Triage Approval': ['qualifiedTriageCalls', 'triageApproval'],
    'Deal Analysis': ['triageApproval', 'dealAnalysis'],
    'Perfect Presentations': ['dealAnalysis', 'perfectPresentations'],
    'Contracts': ['perfectPresentations', 'contracts'],
    'Acquisitions': ['contracts', 'acquisitions'],
    'Pending Deals': ['acquisitions', 'pendingDeals'],
    'Deals': ['pendingDeals', 'deals'],
    'Profit': ['deals', 'profit'],
    'LM STL Median': ['lmStlMedian'],
    'AM STL Median': ['amStlMedian'],
    'DA STL Median': ['daStlMedian'],
    'BiG Checks': ['bigChecks'],
    'Ad Spend': ['marketingExpenses'],
    'Cost Per Approved SLS Q': ['marketingExpenses', 'triageApproval'],
    'Cost Per Contract': ['marketingExpenses', 'contracts'],
    'Cost Per Acquisition': ['marketingExpenses', 'acquisitions'],
    'Cost Per Deal': ['marketingExpenses', 'deals'],
    'Actualized Profit': ['profit'],
    'Projected Profit': ['projectedProfit'],
    'Contracted Profit': ['contractedProfit'],
    'Total Profit': ['profit', 'projectedProfit'],
    'ROAS Actualized': ['profit', 'marketingExpenses'],
    'ROAS Projected': ['projectedProfit', 'marketingExpenses'],
    'ROAS Total': ['profit', 'projectedProfit', 'marketingExpenses'],
    'Closers Ad Spend': ['closersAdSpend'],
    'Closers Leads Created': ['closersLeadsCreated'],
    'Closers Leads Set Prequalified': ['closersLeadsSetPrequalified'],
    'Closers Booking Rate': ['closersLeadsCreated', 'closersBookings'],
    'Closers Cost Per Booking': ['closersAdSpend', 'closersBookings'],
    'Closers Cost Per Qualified Booking': ['closersAdSpend', 'closersQualifiedBookings'],
    'Closers Total Attendance Rate': ['closersAppointments', 'closersTotalAttended'],
    'Closers Offer Rate': ['closersUniqueAttended', 'closersDcOffers'],
    'Closers Close Rate': ['closersUniqueAttended', 'closersDcClosed'],
    'Closers Avg Cash Collected': ['closersPayments'],
    'Closers Avg Revenue Contracted': ['closersPayments'],
    'Setter STL Median': ['setterStlMedian'],
    'Closers Cost Per Lead': ['closersAdSpend', 'closersLeadsCreated'],
    'Closers Cost Per Close': ['closersAdSpend', 'closersDcClosed'],
    'Closers ROAS Cash Collected': ['closersAdSpend', 'closersPayments'],
    'Closers ROAS Projected': ['closersAdSpend', 'closersPayments'],
    // 'Closers ROAS Total': ['closersAdSpend', 'closersPayments'],
};

export default kpiToEndpointMapping;